version: '3.8'

services:
  cli:
    build: .
    command: ["python", "-m", "apps.cli.main", "benchmark", "--quick"]
    volumes:
      - ./libs:/app/libs
      - ./apps:/app/apps
    environment:
      - PYTHONPATH=/app/libs

  api:
    build: .
    command: ["uvicorn", "apps.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./libs:/app/libs
      - ./apps:/app/apps
    environment:
      - PYTHONPATH=/app/libs