name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t wordle-bot:latest .
        
    - name: Test Docker image
      run: |
        docker run --rm wordle-bot:latest --help
