name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        echo "[CI] Start uv sync"
        uv sync --all-extras --frozen
        echo "[CI] Done uv sync"

    - name: Run ruff format check
      run: |
        echo "[CI] Ruff format check"
        uv run ruff format . --check --output-format=github

    - name: Run ruff lint
      run: |
        echo "[CI] Ruff lint"
        uv run ruff check . --diff --output-format=github

    - name: Run tests
      run: |
        uv run pytest tests/ -v

    - name: Test CLI
      run: |
        uv run python main.py --help
        uv run python main.py simulate --target ABOUT --no-display
