name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Run format check
      run: |
        uv run ruff check . --diff
        uv run ruff format . --check

    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Test CLI
      run: |
        python main.py --help
        python main.py simulate --target ABOUT --no-display
