name: Performance

on:
  push:
    branches: [ main, alpha ]
  pull_request:
    branches: [ main, alpha ]
  workflow_dispatch:

jobs:
  performance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Run performance benchmark
      run: |
        PYTHONPATH=libs uv run python -m apps.cli.main benchmark --quick --output-format json --output benchmark-results.json

    - name: Run analytics benchmark
      run: |
        PYTHONPATH=libs uv run python -m apps.cli.main analytics --analysis-type strategy --sample-size 5

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: benchmark-results
        path: benchmark-results.json
        retention-days: 30
