name: Pre-commit

on:
  push:
    branches: [ main, alpha ]
  pull_request:
    branches: [ main, alpha ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Install pre-commit
      run: |
        uv add pre-commit

    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files
