name: Security

on:
  # Disabled - focusing on main CI checks
  # push:
  #   branches: [ main, alpha ]
  # pull_request:
  #   branches: [ main, alpha ]
  # schedule:
  #   - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:  # Only run manually if needed

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --all-extras

    - name: Run safety check
      run: |
        uv add safety
        uv run safety check

    - name: Run bandit security linter
      run: |
        uv add bandit
        uv run bandit -r libs/ apps/ -f json -o bandit-report.json || true

    - name: Upload security report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-report
        path: bandit-report.json
        retention-days: 30
